import type { WeaponDef, WeaponId } from './types';

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  knife: {
    id: 'knife',
    name: 'Knife',
    category: 'melee',
    price: 0,
    damage: 50,
    fireRate: 60,
    magSize: 0,
    reserveAmmo: 0,
    reloadTime: 0,
    spread: 0,
    recoil: 0,
    auto: false,
    range: 3,
  },
  glock: {
    id: 'glock',
    name: 'Glock-18',
    category: 'pistol',
    price: 200,
    damage: 22,
    fireRate: 360,
    magSize: 17,
    reserveAmmo: 68,
    reloadTime: 1.8,
    spread: 0.018,
    recoil: 0.012,
    auto: false,
    range: 60,
  },
  deagle: {
    id: 'deagle',
    name: 'Desert Eagle',
    category: 'pistol',
    price: 700,
    damage: 55,
    fireRate: 240,
    magSize: 7,
    reserveAmmo: 28,
    reloadTime: 2.2,
    spread: 0.01,
    recoil: 0.03,
    auto: false,
    range: 80,
  },
  ak47: {
    id: 'ak47',
    name: 'AK-47',
    category: 'rifle',
    price: 2700,
    damage: 34,
    fireRate: 600,
    magSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.4,
    spread: 0.012,
    recoil: 0.018,
    auto: true,
    range: 120,
  },
  m4: {
    id: 'm4',
    name: 'M4A4',
    category: 'rifle',
    price: 2700,
    damage: 30,
    fireRate: 666,
    magSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.6,
    spread: 0.009,
    recoil: 0.014,
    auto: true,
    range: 120,
  },
  awp: {
    id: 'awp',
    name: 'AWP',
    category: 'sniper',
    price: 4750,
    damage: 115,
    fireRate: 41,
    magSize: 10,
    reserveAmmo: 30,
    reloadTime: 3.0,
    spread: 0.001,
    recoil: 0.05,
    auto: false,
    zoom: true,
    range: 200,
  },
  mp7: {
    id: 'mp7',
    name: 'MP7-SMG',
    category: 'smg',
    price: 1500,
    damage: 22,
    fireRate: 750,
    magSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.0,
    spread: 0.02,
    recoil: 0.012,
    auto: true,
    range: 80,
  },
  mp5: {
    id: 'mp5',
    name: 'MP5-SMG',
    category: 'smg',
    price: 1250,
    damage: 20,
    fireRate: 700,
    magSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.1,
    spread: 0.018,
    recoil: 0.01,
    auto: true,
    range: 80,
  },
};

export const BUYABLE_WEAPONS: WeaponId[] = ['glock', 'deagle', 'ak47', 'm4', 'awp', 'mp7', 'mp5'];
